version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql
      - ./node/mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ospranet

  app:
    image: minorigox/node:app
    container_name: app
    networks:
      - ospranet
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: minorigox/nginx:app
    container_name: nginx
    networks:
      - ospranet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  ospranet:
    driver: bridge
